sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tCWhx9E4pjC28ysYX5j
    access-key-secret: piMUNG13jqlMq5FednaFkLA0ebw1BM
    bucket-name: lqloss-sky
